### PR TITLE
Add tests for Varnish 5.2

### PR DESCRIPTION
**Pull request by syphernl**

### CODE REVIEW

**Review by nstapelbroek — COMMENTED** [review]
Wait, so are we dropping 5.1 or are we just testing fresh releases?

**Comment by syphernl** [comment]
Varnish 5.1 has been retired according to [the website](https://varnish-cache.org/releases/). 
We should focus testing on supported/active releases, which is currently 4.1(.8) and 5.2(.0)

**Comment by nstapelbroek** [comment]
Exactly, but some might still have running 5.1 systems depending on this formula.

**Comment by syphernl** [comment]
What do you propose? That we do include 5.1 even though it has been marked as Retired? If 4.1 works and 5.2 works its fairly safe to assume the same can be said about the versions in between.

**Comment by nstapelbroek** [comment]
I propose we add a statement to the readme explaining something like: Although the system might work on retired releases we're currently only testing the formula on the latest "fresh" releases listed at [Varnish](https://varnish-cache.org/releases/) .

**Comment by nstapelbroek** [comment]
I'll add this to the readme, then we're OK I think :+1:

**Pull request merged**
